name: Auto Update Nodes
on:
  schedule:
    - cron: "0 */2 * * *"  # 每2小时运行一次（UTC时间）
  workflow_dispatch:       # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Fetch Nodes from Target Page
        run: |
          # 抓取目标页面 HTML
          curl -s "https://github.com/leetomlee123/freenode?tab=readme-ov-file" -o page.html
          # 提取节点链接（根据实际页面调整正则表达式）
          grep -Eo 'ss://[^"<]+|vmess://[^"<]+|trojan://[^"<]+' page.html > dy
          rm page.html

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dy
          git commit -m "Auto-update nodes from leetomlee123/freenode"
          git push
